Write-Output "============================================"
Write-Output "  ⚠️ 此脚本已弃用，请改用 safe-switch-57321.ps1"
Write-Output "============================================"
Write-Output ""
Write-Output "recover-57321.ps1 会自动全量覆写 config.toml，"
Write-Output "用旧的硬编码值覆盖当前配置，导致丢失插件和环境变量。"
Write-Output ""
Write-Output "正确的切换方法（仅改 base_url，安全）："
Write-Output ""
Write-Output "  cd C:\Users\DEWK\Documents\省流助手v3.0"
Write-Output "  PowerShell -ExecutionPolicy Bypass .\safe-switch-57321.ps1"
Write-Output ""
Write-Output "然后重启 Codex 即可切回 57321"
Write-Output ""
Write-Output "旧版脚本已备份为 recover-57321.ps1.WARNING-DANGER"
